### ISSUE TITLE
[Bug]: Crash when adding burnables to campfire

### ISSUE THREAD

**Issue by Izre** [cech12/UnlitCampfire#25] opened 2023-08-18 08:37 UTC
### Minecraft Version

1.19.4

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Mod Version

unlitcampfire-forge-1.19-1.7.1.0

### Describe the Issue

When trying to add burnables materials into campfire, the game crashes.
When you try to interact with the right mouse button with a campfire, the game also crashes.
In new versions 1.20+ this bug is fixed I would like fixes for 1.19.2-1.19.4 thanks

**Comment by cech12** [comment] 2023-08-18 08:39
Thanks for your report! I will reproduce it and try to fix that for 1.19.2 and 1.19.4.

**Comment by cech12** [comment] 2023-08-18 11:18
@Izre Can you add a crash log?

**Comment by cech12** [comment] 2023-08-19 05:53
I could not reproduce the crash in 1.19.2 . I could reproduce it in 1.19.3 and 1.19.4. 

It is fixed in the upcoming version 1.19.4-1.7.2.0 (for 1.19.4)

**Closed as completed by cech12** 2023-08-19 05:53 UTC
Labels: bug
